# This is a basic workflow to help you get started with Actions

name: pack-archlinux

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run script
        run: cd zff-reload/ && bash pack-arch.sh
      
      - name: Makepkg Build and Check
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1.1.8
        with:
          pkgdir: ./zff-reload/archlinux
      
      - uses: actions/upload-artifact@v3
        with:
          name: Zff-archlinux
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
